In [102]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir("C:/Users/16472/Desktop/Machine Learning/ANN")

In [103]:
## Tensorflow Version
tf.__version__

'2.3.1'

# (Part 1) Load the Data

In [104]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset
x = dataset.iloc[:, 3:-1].values # select everything from columns indices (3 to end)
y = dataset.iloc[:, -1].values

In [105]:
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [106]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

### Change variable values betweens columns 0 and 2 to integer values

In [107]:
print(x) 

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [108]:
# One Hot encoding for geography
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

### One hot encoding

So we typically use one hot encoding when we have more than one variable to apply to the training model.

In [109]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [110]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [118]:
print(X_train.shape)
print(X_test.shape)

(8000, 12)
(2000, 12)


### By specifying the train_size as 0.2, we aim to put 80% of the data into our training set, and the rest of the data into the test set. 

## Feature Scaling

#### THE MOST IMPORTANT PART IN MACHINE LEARNING ALGORITHMS!!!

e.g normalization, standardization

In [119]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# (Step 2) Building the ANN

In [120]:
ann = tf.keras.models.Sequential() # represents our artificial neural network

In [121]:
# Adding the input layer and the first hidden layer
# How do we know how many neurons (UNITS) that we want.
# It's more of a guess.

hidden_neurons = 6
ann.add(tf.keras.layers.Dense(units=hidden_neurons, activation='relu')) # relu is a rectifier activation function

In [122]:
# Add a second hidden layer.
# We can have as many hidden layers as we want.
hidden_neurons = 6
ann.add(tf.keras.layers.Dense(units=hidden_neurons, activation='relu')) # relu is a rectifier activation function

In [123]:
# Number of dimensions of the output (0 or 1. There 1 neuron.)
# Sigmoid is the probability of it being a yes or a no. (0 or 1)
# Sigmoid function predicts! Rather than giving a definitive yes or no.
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# (Step 3) Training the ANN

Now we have created an "artificial brain"!

Next step is to train our brain.

In [135]:
# adam optimizer is used for stochastic gradient descent.
# loss parameter is binary_crosseentropy since we are looking at a binary outcome.
# metrics

ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [136]:
# Where we are training the dataset on the ANN

ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 503us/step - loss: 0.3321 - accuracy: 0.8645
Epoch 2/100
250/250 [==============================] - 0s 491us/step - loss: 0.3315 - accuracy: 0.8621
Epoch 3/100
250/250 [==============================] - 0s 495us/step - loss: 0.3316 - accuracy: 0.8624
Epoch 4/100
250/250 [==============================] - 0s 507us/step - loss: 0.3313 - accuracy: 0.8629
Epoch 5/100
250/250 [==============================] - 0s 475us/step - loss: 0.3318 - accuracy: 0.8626
Epoch 6/100
250/250 [==============================] - 0s 519us/step - loss: 0.3309 - accuracy: 0.8637
Epoch 7/100
250/250 [==============================] - 0s 547us/step - loss: 0.3313 - accuracy: 0.8629
Epoch 8/100
250/250 [==============================] - 0s 512us/step - loss: 0.3312 - accuracy: 0.8644
Epoch 9/100
250/250 [==============================] - 0s 447us/step - loss: 0.3316 - accuracy: 0.8639
Epoch 10/100
250/250 [==============================] - 0s 446us/step - l

250/250 [==============================] - 0s 491us/step - loss: 0.3290 - accuracy: 0.8631
Epoch 80/100
250/250 [==============================] - 0s 475us/step - loss: 0.3290 - accuracy: 0.8629
Epoch 81/100
250/250 [==============================] - 0s 491us/step - loss: 0.3292 - accuracy: 0.8626
Epoch 82/100
250/250 [==============================] - 0s 503us/step - loss: 0.3283 - accuracy: 0.8645
Epoch 83/100
250/250 [==============================] - 0s 489us/step - loss: 0.3291 - accuracy: 0.8630
Epoch 84/100
250/250 [==============================] - 0s 477us/step - loss: 0.3291 - accuracy: 0.8637
Epoch 85/100
250/250 [==============================] - 0s 467us/step - loss: 0.3290 - accuracy: 0.8622
Epoch 86/100
250/250 [==============================] - 0s 467us/step - loss: 0.3290 - accuracy: 0.8630
Epoch 87/100
250/250 [==============================] - 0s 455us/step - loss: 0.3289 - accuracy: 0.8634
Epoch 88/100
250/250 [==============================] - 0s 483us/step - loss:

The <b>batch size</b> is a hyperparameter that defines the number of samples to work through before updating the internal model parameters.

The <b>number of epochs</b> is a hyperparameter that defines the number times that the learning algorithm will work through the entire training dataset.


The batch size is a number of samples processed before the model is updated.
The number of epochs is the number of complete passes through the training dataset.

There are no magic rules for how to configure these parameters. You must try different values and see what works best for your problem.

# Worked Example
Finally, let’s make this concrete with a small example.

Assume you have a dataset with 200 samples (rows of data) and you choose a batch size of 5 and 1,000 epochs.

This means that the dataset will be divided into 40 batches, each with five samples. The model weights will be updated after each batch of five samples.

This also means that one epoch will involve 40 batches or 40 updates to the model.

With 1,000 epochs, the model will be exposed to or pass through the whole dataset 1,000 times. That is a total of 40,000 batches during the entire training process.

# (Part 4) Testing our Hypothesis

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [143]:
# We have to scale the prediction values using sc.transform

print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

[[0.04288873]]


Our model predicts that the customer will stay!

<em>Based on our given data</em>

In [150]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# y pred is our prediction if the customer stays or leaves.
# y test is the true value for whether the customer stays or leaves. 

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [151]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1521   74]
 [ 206  199]]


0.86